schoolproject/schoolapp/urls.py
from django.contrib import admin
from . import views
from django.urls import path
app_name='schoolapp'
urlpatterns = [
   path('',views.index,name='index'),
   path('register',views.register,name='register'),
   path('login',views.login,name='login'),
   path('logout',views.logout,name='logout'),
   path('new/',views.new,name='new'),
   path('student_form/', views.student_form, name='student_form'),
   path('ajax/load-courses/',views.load_courses, name='ajax_load_courses'),
   path('',views.allCourceDep,name='allCourceDep'),
]

schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

schoolproject/schoolapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=250, unique=True)
    wikipedia_url = models.URLField(blank=True, null=True)
    class Meta:
        ordering=('name',)
        verbose_name = 'department'
        verbose_name_plural = 'departments'

    def __str__(self):
        return '{}'.format(self.name)

class Course(models.Model):
    name = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.name)

class Material(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=255)
    dob = models.DateField()
    age = models.IntegerField()
    GENDER_CHOICES = [
        ('Male', 'Male'),('Female', 'Female'),('Other', 'Other'),
    ]
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=10)
    email = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=255, choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return')])
    materials_provide = models.ManyToManyField(Material)

    def __str__(self):
        return self.name

schoolproject/schoolapp/forms.py
from django import forms
from .models import Department, Material, Student, Course


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','dob','age','gender','phone_number','email','address','department','course','purpose','materials_provide']

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['materials_provide'].widget = forms.CheckboxSelectMultiple()
        self.fields['materials_provide'].queryset = Material.objects.all()
        self.fields['course'].queryset = Course.objects.all()
        self.fields['gender'].widget = forms.RadioSelect(choices=Student.GENDER_CHOICES)
        self.fields['dob'].widget = forms.DateInput(attrs={'type': 'date'})

schoolproject/schoolapp/views.py
from schoolapp.models import Department,Course
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import StudentForm
from django.http import JsonResponse
from django.contrib.auth import authenticate, login as auth_login

# Create your views here./
def index(request):
    return render(request,'home.html')


# def login(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#
#         user = auth.authenticate(username=username,password=password)
#         if user is not None:
#             auth.login(request,user)
#             return redirect('/new')
#         else:
#             messages.info(request,'invalid credential')
#             return redirect('/')
#     return render(request,'login.html')
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.check_password(password):
                auth_login(request, user)
                return redirect('/new')
            else:
                messages.error(request, 'Incorrect password')
        else:
            messages.error(request, 'Invalid username or password')

    return render(request, 'login.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirmation_password = request.POST['confirmation_password']
        if not username or not password or not confirmation_password:
            messages.info(request, 'Please fill in all the required fields')
            return redirect('/register')
        if password == confirmation_password:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username already exist")
                return redirect('/register')
            else:
                 user = User.objects.create_user(username=username,password=password)
                 user.save();
                 return redirect('/login')
        else:
            messages.info(request,'password not matched')
            return redirect('/register')
        return redirect('/')
    return render(request, 'register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def allCourceDep(request):
    return render(request,'home.html')

def student_form(request):
    departments = Department.objects.all()
    courses = Course.objects.all()
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'confirmation.html', {'message': 'Order Confirmed'})
    else:
        form = StudentForm()
    return render(request, 'student_form.html', {'form': form,'departments':departments, 'courses': courses})

def load_courses(request):
    department_id = request.GET.get('department')
    courses = Course.objects.filter(department_id=department_id).values('id', 'name')
    return JsonResponse(list(courses), safe=False)

def new(request):
    return render(request,'new.html')

schoolproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <!-- CSS only -->
      <link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css " rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
     <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js " integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/c5fec5db8c.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}">
<br>
    <header>
    <center>
        <a href="{% url 'schoolapp:allCourceDep' %}"> <img src="{% static 'img/logo.png' %}" alt="loging"></a>
    </center>
</header><br>
</head>
<body>
<div>
    {% include 'navbar.html' %}
    {% block body %}{% endblock %}
</div><br>
    {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src=" https://code.jquery.com/jquery-3.2.1.slim.min.js " integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src=" https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src=" https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

schoolproject/templates/confirmation.html
{% load static %}
<style>

    .message{
    color:#006400;
    text-align: center;
    padding: 250px;
}

.return-button {
        background-color: #006400;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        display: inline-block;
        margin-top: 20px;
    }

    .return-button:hover {
        background-color: #004d00;
    }
</style>
<body>
<link rel="stylesheet"  href="{% static 'css/style.css' %}">
<div class="container">
  <div class="message">
      <div>
          <h1>{{ message }}</h1>
      </div>
      <div>
          <a href="{% url 'schoolapp:index' %}" class="return-button">Return to Home Page</a>
      </div>
</div>
</div>
</body>

schoolproject/templates/footer.html
<div class="footer fixed-bottom my_footer">
    <p class="text-center">&copy; ABC Education pvt ltd.</p>
</div>

schoolproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
<div class="row justify-content-center">
    <img class="my_image_padding" src="{% static 'img/banner.png' %}" alt="Our products">
</div>
<br>
<div>

    <h1 class="text-center my_title">About Us</h1>
    <p class="text-justify">University comes with lots of features that a modern WordPress education theme need to have. Some of those features include: responsive design, Slider Revolution included, Facebook & Disqus comments integration, Event Management, Course Management, and Built-in Event Calendar. We believe University is one of the perfect WordPress themes for education organizations’ websites. Furthermore, our educational WordPress theme includes 7 home page demos which you can import into your website within few clicks. You are also able to easily customize the theme as your liking by using its powerful Theme Options panel and drag-drop page builder.</p>
</div>
</div>
<br>
<br>

{% endblock %}

schoolproject/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row mt-2 mb-5">
    <div class="container-fluid d-flex align-items-center justify-content-center" style="min-height: 68vh;">
        <div class="card-container card col-sm-6 col-lg-4" style="box-shadow: 0 0 10px #006400; padding: 10px; background-color:#003300;">
            <h2 class="text-center mb-3" style="color: #FFFAF0;">Login</h2>
            <form action="login" method="POST">
                {% csrf_token %}
                <div class="mb-2">
                    <label style="color: #FFFAF0;">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter your username">
                </div>
                <div class="mb-2">
                    <label style="color: #FFFAF0;">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Enter your password">
                </div>
                <br>
                <button type="submit" class="btn btn-success btn-lg btn-block mb-4">Login</button>
            </form>
             <p class="mt-3 text-center" style="color: #FFFAF0;">Don't have an account? <a href="{% url 'schoolapp:register' %}" class="text-primary">Register here</a>.</p>
            {% for msg in messages %}
            <p class="error-message mt-3 text-center" style="color: #ff0000;">{{ msg }}.</p>
            {% endfor %}
        </div>
    </div>
    </div>
</div>
{% endblock %}

schoolproject/templates/navbar.html
<nav class="navbar navbar-expand-lg" style="background-color:#006400;">
    <div class="container-fluid">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'schoolapp:index' %}" style="color:#FFFAF0;">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'schoolapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#FFFAF0;">
          Department
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'schoolapp:allCourceDep' %}">All Department</a>
          {% for dep in links %}
          <a class="dropdown-item" href="{{ dep.wikipedia_url }}">{{dep.name}}</a>
          {% endfor %}
        </div>
        </li>
      <li class="nav-item">
          {% if user.is_authenticated %}
          <a  class="nav-link" style="color:#FFFAF0;">Hello {{user.username}}</a>
      <li><a class="nav-link" href="{% url 'schoolapp:logout' %}" style="color:#FFFAF0;">Log Out</a></li>
          {% else %}
      <li><a class="nav-link" href="{% url 'schoolapp:register' %}" style="color:#FFFAF0;">Registration</a></li>
         <li><a class="nav-link" href="{% url 'schoolapp:login' %}" style="color:#FFFAF0;">Log In</a></li>
         {% endif %}

      </li>
    </ul>
    </div>
  </div>
</nav>

schoolproject/templates/new.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="container">
  <div class="form-link mt-5 mb-5">
    <div class="container-fluid d-flex align-items-center justify-content-center" style="min-height: 50vh;">
      <a href="{% url 'schoolapp:student_form' %}">
        <button class="btn btn-success btn-lg">
          <h2>Click here to fill the Student Form</h2>
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock %}

schoolproject/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="container">
    <div class="row mt-2 mb-5">
    <div class="container-fluid d-flex align-items-center justify-content-center" style="min-height: 70vh;">
        <div class="card-container card col-md-6 col-lg-4" style="box-shadow: 0 0 10px #006400; padding: 10px; background-color:#003300;">
            <h2 class="text-center mb-3" style="color: #FFFAF0;">Registration</h2>
            <form action="register" method="POST">
                {% csrf_token %}
                <div class="mb-2">
                    <label style="color: #FFFAF0;">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter your username">
                </div>
                <div class="mb-2">
                    <label style="color: #FFFAF0;">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Enter your password">
                </div>
                 <div class="mb-2">
                    <label style="color: #FFFAF0;">Confirmation Password</label>
                    <input type="password" class="form-control" name="confirmation_password" placeholder="Enter confirmation password">
                </div><br>
                <button type="submit" class="btn btn-success btn-lg btn-block mb-4">Register</button>
            </form>
            {% for msg in messages %}
                <p class="error-message mt-3 text-center" style="color: #ff0000;">{{ msg }}.</p>
            {% endfor %}
        </div>
    </div>
        </div>
    </div>

{% endblock %}

schoolproject/templates/student_form.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<style>
    .custom-card {
        max-width: 800px;
        margin: auto;
        margin-top: 50px;
        margin-bottom:50px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    .card-header {
        background-color: #006400;
        color: white;
        text-align: center;
        padding: 20px;
    }

    .card-body {
        padding: 30px;
    }

    .form-group {
        margin-bottom: 30px;
    }
     .form-label {
        font-weight: bold;
        font-size:15px;
        margin-right: 50px;
        margin-bottom: 10px;
    }

    .form-button {
        width: 100%;
        padding: 10px;
        box-sizing: border-box;
        border: none;
        border-radius: 5px;
        background-color: #006400;
        color: white;
        cursor: pointer;
    }
    .form-button:hover {
        background-color: #004d00;
    }
</style>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card custom-card">
                <div class="card-header">
                    <h1>STUDENTS FORM</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'schoolapp:student_form' %}" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_name" class="form-label">Name</label>
                                {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_dob" class="form-label">DOB</label>
                                {{ form.dob }}
                            </div>
                        <div class="form-group">
                            <label for="id_age" class="form-label">Age</label>
                                {{ form.age }}
                            </div>
                         <div class="form-group">
                             <label for="id_gender" class="form-label">Gender</label>
                                 {% for radio in form.gender %}
                                 <div class="form-check form-check-inline">
                                     {{ radio }}
                                 </div>
                                 {% endfor %}
                             </div>
                        <div class="form-group ">
                            <label for="id_phone_number" class="form-label">Enter your Number</label>
                                {{ form.phone_number }}
                        </div>
                        <div class="form-group">
                            <label for="id_mail" class="form-label">Email-Id</label>
                                {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="id_address" class="form-label">Address</label>
                                {{ form.address }}
                        </div>
                        <div class="form-group">
                            <label for="id_department" class="form-label">Department</label>
                               {{form.department}}
                        </div>

                        <div class="form-group">
                            <label for="id_course" class="form-label">Courses</label>
                                {{ form.course }}
                        </div>

                        <div class="form-group">
                            <label for="id_purpose" class="form-label">Purpose</label>
                                {{ form.purpose }}
                        </div>

                        <div class="form-group">
                            <label for="id_materials_provide" class="form-label">Materials</label>
                                {{ form.materials_provide }}
                        </div>

                        <div class="form-group">
                                <input type="submit" value="Submit" class="form-button btn btn-success btn-lg mt-3">
                        </div>
</form>
                        </div>
                </div>
            </div>
            </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Function to update the course dropdown based on the selected department
        function updateCourses() {
            var selectedDepartment = document.getElementById('id_department').value;

            // Fetch courses for the selected department using AJAX
            fetch(`/ajax/load-courses/?department=${selectedDepartment}`)
                .then(response => response.json())
                .then(data => {
                    // Update the course dropdown
                    var courseDropdown = document.getElementById('id_course');
                    courseDropdown.innerHTML = '<option value="">---------</option>';
                    data.forEach(course => {
                        var option = document.createElement('option');
                        option.text = course.name;
                        option.value = course.id;
                        courseDropdown.add(option);
                    });
                })
                .catch(error => console.error('Error:', error));
        }

        // Attach the updateCourses function to the change event of the department dropdown
        document.getElementById('id_department').addEventListener('change', updateCourses);

        // Trigger the change event initially to set up the initial state
        document.getElementById('id_department').dispatchEvent(new Event('change'));
    });
</script>

{% endblock %}